using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace uploader
{
    internal class LocalizationHelper
    {

		public static LocalizationBase Base;

		static readonly Dictionary<string, string> Languages = new Dictionary<string, string>(13)
		{
			["English"] = "{\"MainForm_DragFile\":\"Drag file here\",\"MainForm_More\":\"Settings\",\"SettingsForm_Title\":\"Settings\",\"SettingsForm_General\":\"General settings\",\"SettingsForm_Key\":\"API key\",\"SettingsForm_Get\":\"Get API key\",\"SettingsForm_Language\":\"Language\",\"SettingsForm_Save\":\"Save\",\"SettingsForm_Open\":\"Open settings file\",\"SettingsForm_DirectUpload\":\"Automatic Upload?\",\"SettingsForm_Reset\":\"Reset all settings?\",\"SettingsForm_Sure\":\"Are you sure?\",\"SettingsForm_Context\":\"Add to Context Menu?\",\"SettingsForm_ResetBtn\":\"Reset\",\"UploadForm_Info\":\"File information\",\"UploadForm_Upload\":\"Upload\",\"UploadForm_Cancel\":\"Cancel\",\"UploadForm_NoApiKey\":\"You have not entered an API key. Please go to settings and add one.\",\"UploadForm_InvalidLength\":\"Invalid API key length. The key must contain 64 characters.\",\"UploadForm_InvalidKey\":\"Invalid API key\",\"Message_Idle\":\"Idle.\",\"Message_Init\":\"Initializing...\",\"Message_Check\":\"Checking...\",\"Message_Upload\":\"Uploading...\",\"Message_NoLink\":\"No permalink found in response!\",\"Message_NoSettings\":\"No settings file exists.\",\"Message_Saved\":\"Settings saved.\"}",
			["Czech"] = "{ \"MainForm_DragFile\": \"Přesuňte soubor zde\", \"MainForm_More\": \"Nastavení\", \"SettingsForm_Title\": \"Nastavení\", \"SettingsForm_General\": \"Obecné nastavení\", \"SettingsForm_Key\": \"API klíč\", \"SettingsForm_Get\": \"Získat API klíč\", \"SettingsForm_Language\": \"Jazyk\", \"SettingsForm_Save\": \"Uložit\", \"SettingsForm_Open\": \"Otevřit soubor nastavení\", \"SettingsForm_DirectUpload\": \"Automatické nahrávání?\", \"UploadForm_Info\": \"Informace o souboru\", \"UploadForm_Upload\": \"Nahrát\", \"UploadForm_Cancel\": \"Zrušit\", \"UploadForm_NoApiKey\": \"Nepřidali jste API klíč. Jděte to nastavení a přidejte ho.\", \"UploadForm_InvalidLength\": \"Přidali jste API klíč, ale nemá správnou délku. Měl by mít 64 znaků.\", \"UploadForm_InvalidKey\": \"Špatný API klíč\", \"Message_Idle\": \"Nic.\", \"Message_Init\": \"Inicializace...\", \"Message_Check\": \"Kontrola...\", \"Message_Upload\": \"Nahrávání...\", \"Message_NoLink\": \"Zádný odkaz v odpovědi serveru!\", \"Message_NoSettings\": \"Soubor nastavení neexistuje.\", \"Message_Saved\": \"Nastavení uloženo.\",\"SettingsForm_Reset\":\"Resetovat všechna nastavení?\",\"SettingsForm_Sure\":\"Jsi si jistá?\",\"SettingsForm_Context\":\"Přidat do kontextové nabídky?\",\"SettingsForm_ResetBtn\":\"Resetovat\" }",
			["French"] = "{ \"MainForm_DragFile\": \"Glissez le fichier ici\", \"MainForm_More\": \"Réglages\", \"SettingsForm_Title\": \"Paramètres\", \"SettingsForm_General\": \"Paramètres généraux\", \"SettingsForm_Key\": \"Clé API\", \"SettingsForm_Get\": \"Obtenir une clé API\", \"SettingsForm_Language\": \"Langue\", \"SettingsForm_Save\": \"Sauvegarder\", \"SettingsForm_Open\": \"Ouvrir le fichier des paramètres\", \"UploadForm_Info\": \"Informations sur le fichier\", \"UploadForm_Upload\": \"Mettre en ligne\", \"UploadForm_Cancel\": \"Annuler\", \"UploadForm_NoApiKey\": \"Vous n'avez pas saisi de clé API. Veuillez accéder aux paramètres et en ajouter un.\", \"UploadForm_InvalidLength\": \"Vous avez entré une clé API, mais la clé n'a pas une longueur valide. La clé doit contenir 64 caractères.\", \"UploadForm_InvalidKey\": \"Invalid API key\", \"Message_Idle\": \"Prêt.\", \"Message_Init\": \"Initialisation...\", \"Message_Check\": \"Vérification...\", \"Message_Upload\": \"Mise en ligne...\", \"Message_NoLink\": \"Aucun permalien trouvé en réponse!\", \"Message_NoSettings\": \"Aucun fichier de paramètres n'existe.\", \"Message_Saved\": \"Paramètres sauvegardés.\",\"SettingsForm_Reset\":\"Réinitialiser tous les réglages?\",\"SettingsForm_Sure\":\"Es-tu sûr?\",\"SettingsForm_Context\":\"Ajouter au menu contextuel ?\",\"SettingsForm_ResetBtn\":\"Réinitialiser\",\"SettingsForm_DirectUpload\":\"Téléchargement automatique ?\" }",
			["German"] = "{ \"MainForm_DragFile\": \"Datei hierher ziehen\", \"MainForm_More\": \"Einstellungen\", \"SettingsForm_Title\": \"Einstellungen\", \"SettingsForm_General\": \"Allgemeine Einstellungen\", \"SettingsForm_Key\": \"API-Key\", \"SettingsForm_Get\": \"API-Schlüssel abrufen\", \"SettingsForm_Language\": \"Sprache\", \"SettingsForm_Save\": \"Speichern\", \"SettingsForm_Open\": \"Einstellungsdatei öffnen\", \"UploadForm_Info\": \"Dateiinformationen\", \"UploadForm_Upload\": \"Hochladen\", \"UploadForm_Cancel\": \"Abbrechen\", \"UploadForm_NoApiKey\": \"You have not entered an API key. Please go to settings and add one.\", \"UploadForm_InvalidLength\": \"Sie haben einen API-Schlüssel eingegeben, aber der Schlüssel hat keine gültige Länge. Schlüssel sollte 64 Zeichen enthalten.\", \"UploadForm_InvalidKey\": \"Invalid API key\", \"Message_Idle\": \"Leerlauf.\", \"Message_Init\": \"Initialisieren ...\", \"Message_Check\": \"Überprüfen ...\", \"Message_Upload\": \"Hochladen ...\", \"Message_NoLink\": \"Kein Permalink als Antwort gefunden!\", \"Message_NoSettings\": \"Es ist keine Einstellungsdatei vorhanden.\", \"Message_Saved\": \"Einstellungen gespeichert.\",\"SettingsForm_Reset\":\"Alle Einstellungen zurücksetzen?\",\"SettingsForm_Sure\":\"Bist du sicher?\",\"SettingsForm_Context\":\"Zum Kontextmenü hinzufügen?\",\"SettingsForm_ResetBtn\":\"Zurücksetzen\",\"SettingsForm_DirectUpload\":\"Automatischer Upload?\" }",
			["Italian"] = "{ \"MainForm_DragFile\": \"Sposta il file qui\", \"MainForm_More\": \"Impostazioni\", \"SettingsForm_Title\": \"Impostazioni\", \"SettingsForm_General\": \"Impostazioni generali\", \"SettingsForm_Key\": \"Chiave API\", \"SettingsForm_Get\": \"Ottieni chiave API\", \"SettingsForm_Language\": \"Lingua\", \"SettingsForm_Save\": \"Salva\", \"SettingsForm_Open\": \"Apri impostazioni dal file\", \"SettingsForm_DirectUpload\": \"Caricamento automatico?\", \"UploadForm_Info\": \"Informazioni del file\", \"UploadForm_Upload\": \"Carica\", \"UploadForm_Cancel\": \"Cancella\", \"UploadForm_NoApiKey\": \"Non hai inserito una chiave API. Per favore vai nelle impostazioni e aggiungine una.\", \"UploadForm_InvalidLength\": \"Lunghezza della chiave API non valida. La chiave deve contenere 64 caratteri.\", \"UploadForm_InvalidKey\": \"Chiave API invalida\", \"Message_Idle\": \"Inattivo.\", \"Message_Init\": \"Inizializzazione...\", \"Message_Check\": \"Controllo...\", \"Message_Upload\": \"Caricamento...\", \"Message_NoLink\": \"Nessun permalink trovato nella risposta!\", \"Message_NoSettings\": \"Non esiste un file di impostazioni.\", \"Message_Saved\": \"Impostazioni salvate.\",\"SettingsForm_Reset\":\"Resettare tutte le impostazioni?\",\"SettingsForm_Sure\":\"Sei sicuro?\",\"SettingsForm_Context\":\"Aggiungere al menu contestuale?\",\"SettingsForm_ResetBtn\":\"Ripristina\" }",
			["PortugueseBr"] = "{ \"MainForm_DragFile\": \"Arrastar arquivo aqui\", \"MainForm_More\": \"Configurações\", \"SettingsForm_Title\": \"Configurações\", \"SettingsForm_General\": \"Configurações gerais\", \"SettingsForm_Key\": \"Chave de API\", \"SettingsForm_Get\": \"Obter chave API\", \"SettingsForm_Language\": \"Idioma\", \"SettingsForm_Save\": \"Salvar\", \"SettingsForm_Open\": \"Abrir arquivo de configurações\", \"SettingsForm_DirectUpload\": \"Carregamento automático?\", \"UploadForm_Info\": \"Informação do arquivo\", \"UploadForm_Upload\": \"Enviar\", \"UploadForm_Cancel\": \"Cancelar\", \"UploadForm_NoApiKey\": \"Você não inseriu uma chave API. Vá para as configurações e adicione uma.\", \"UploadForm_InvalidLength\": \"Comprimento de chave de API inválido. A chave deve conter 64 caracteres.\", \"UploadForm_InvalidKey\": \"Chave de API inválida\", \"Message_Idle\": \"Ocioso.\", \"Message_Init\": \"Inicializando...\", \"Message_Check\": \"Verificando...\", \"Message_Upload\": \"Enviando...\", \"Message_NoLink\": \"Nenhum link permanente encontrado na resposta!\", \"Message_NoSettings\": \"Nenhum arquivo de configurações existe.\", \"Message_Saved\": \"Configurações salvas.\",\"SettingsForm_Reset\":\"Redefinir todas as configurações?\",\"SettingsForm_Sure\":\"Tem certeza?\",\"SettingsForm_Context\":\"Adicionar ao menu de contexto?\",\"SettingsForm_ResetBtn\":\"Redefinir\" }",
			["Russian"] = "{ \"MainForm_DragFile\": \"Перетащите файл сюда\", \"MainForm_More\": \"Настройки\", \"SettingsForm_Title\": \"Настройки\", \"SettingsForm_General\": \"Общие настройки\", \"SettingsForm_Key\": \"API key\", \"SettingsForm_Get\": \"Получить API key\", \"SettingsForm_Language\": \"Язык\", \"SettingsForm_Save\": \"Сохранить\", \"SettingsForm_Open\": \"Открыть файл настроек\", \"UploadForm_Info\": \"Информация о файле\", \"UploadForm_Upload\": \"Отправить\", \"UploadForm_Cancel\": \"Отмена\", \"UploadForm_NoApiKey\": \"Вы не ввели API key. Пожалуйста, перейдите в настройки и добавьте один.\", \"UploadForm_InvalidLength\": \"Недопустимая длина API key. Он должен содержать 64 символа.\", \"UploadForm_InvalidKey\": \"Неверный API key\", \"Message_Idle\": \"Ожидание.\", \"Message_Init\": \"Инициализация...\", \"Message_Check\": \"Проверка...\", \"Message_Upload\": \"Отправка...\", \"Message_NoLink\": \"Нет ссылки в ответе сервера!\", \"Message_NoSettings\": \"Файл настроек не существует.\", \"Message_Saved\": \"Настройки сохранены.\",\"SettingsForm_Reset\":\"Сбросить все настройки?\",\"SettingsForm_Sure\":\"Уверены ли вы?\",\"SettingsForm_Context\":\"Добавить в контекстное меню?\",\"SettingsForm_ResetBtn\":\"Перезагрузить\",\"SettingsForm_DirectUpload\":\"Автоматическая загрузка?\" }",
			["SimplifiedChinese"] = "{ \"MainForm_DragFile\": \"请把文檔放到这里\", \"MainForm_More\": \"设置\", \"SettingsForm_Title\": \"设置\", \"SettingsForm_General\": \"一般设置\", \"SettingsForm_Key\": \"API 密钥\", \"SettingsForm_Get\": \"获取 API密钥\", \"SettingsForm_Language\": \"语言\", \"SettingsForm_Save\": \"保存\", \"SettingsForm_Open\": \"打开设置文檔\", \"SettingsForm_DirectUpload\": \"自动上传？\", \"UploadForm_Info\": \"文檔信息\", \"UploadForm_Upload\": \"上传\", \"UploadForm_Cancel\": \"取消\", \"UploadForm_NoApiKey\": \"您没有输入一个有效的 API密钥。请点选设置并添加一个。\", \"UploadForm_InvalidLength\": \"错误的 API密钥长度。密钥必须包含 64个字符。\", \"UploadForm_InvalidKey\": \"无用的API密钥\", \"Message_Idle\": \"闲置。\", \"Message_Init\": \"初始化...\", \"Message_Check\": \"正在检查...\", \"Message_Upload\": \"正在上传...\", \"Message_NoLink\": \"检查中没有找到有效链接！\", \"Message_NoSettings\": \"没有设置文檔存在。\", \"Message_Saved\": \"设置已储存。\",\"SettingsForm_Reset\":\"重置所有设置？\",\"SettingsForm_Sure\":\"你确定吗？\",\"SettingsForm_Context\":\"添加到上下文菜单？\",\"SettingsForm_ResetBtn\":\"重启\" }",
			["Slovenian"] = "{ \"MainForm_DragFile\": \"Povlecite datoteko sem\", \"MainForm_More\": \"Nastavitve\", \"SettingsForm_Title\": \"Nastavitve\", \"SettingsForm_General\": \"Splošne nastavitve\", \"SettingsForm_Key\": \"API ključ\", \"SettingsForm_Get\": \"Pridobi API ključ\", \"SettingsForm_Language\": \"Jezik\", \"SettingsForm_Save\": \"Shrani\", \"SettingsForm_Open\": \"Odprite datoteko z nastavitvami\", \"SettingsForm_DirectUpload\": \"Samodejno nalaganje?\", \"UploadForm_Info\": \"Informacije o datoteki\", \"UploadForm_Upload\": \"Naloži\", \"UploadForm_Cancel\": \"Prekliči\", \"UploadForm_NoApiKey\": \"Niste vnesli API ključa. Pojdite v nastavitve in da vnesite.\", \"UploadForm_InvalidLength\": \"Neveljavna dolžina API ključa. Ključ mora vsebovati 64 znakov.\", \"UploadForm_InvalidKey\": \"Neveljaven API ključ\", \"Message_Idle\": \"V mirovanju.\", \"Message_Init\": \"Zaganjanje...\", \"Message_Check\": \"Preverjanje...\", \"Message_Upload\": \"Nalaganje...\", \"Message_NoLink\": \"V odgovoru ni nobene trajne povezave!\", \"Message_NoSettings\": \"Datoteka z nastavitvami ne obstaja.\", \"Message_Saved\": \"Nastavitve so shranjene.\",\"SettingsForm_Reset\":\"Ponastaviti vse nastavitve?\",\"SettingsForm_Sure\":\"Ali si prepričan?\",\"SettingsForm_Context\":\"Dodati v kontekstni meni?\",\"SettingsForm_ResetBtn\":\"Ponastaviti\" }",
			["Thai"] = "{ \"MainForm_DragFile\": \"วางไฟล์ลง ที่นี่..\", \"MainForm_More\": \"การตั้งค่า\", \"SettingsForm_Title\": \"ตั้งค่า\", \"SettingsForm_General\": \"ตั้งค่าทั่วไป\", \"SettingsForm_Key\": \"API Key\", \"SettingsForm_Get\": \"รับ API Key\", \"SettingsForm_Language\": \"ภาษา\", \"SettingsForm_Save\": \"บันทึก\", \"SettingsForm_Open\": \"เปิดไฟล์การตั้งค่า\", \"SettingsForm_DirectUpload\": \"อัพโหลดอัตโนมัติ?\", \"UploadForm_Info\": \"ข้อมูลของไฟล์\", \"UploadForm_Upload\": \"อัพโหลด\", \"UploadForm_Cancel\": \"ยกเลิก\", \"UploadForm_NoApiKey\": \"คุณยังไม่ได้ป้อน API Key โปรดไปที่การตั้งค่าและเพิ่ม\", \"UploadForm_InvalidLength\": \"ความยาวของ API Key ไม่ถูกต้อง Key ต้องมีอักขระ 64 ตัว\", \"UploadForm_InvalidKey\": \"API Key ไม่ถูกต้อง\", \"Message_Idle\": \"ว่างเปล่า\", \"Message_Init\": \"กำลังเริ่มต้น...\", \"Message_Check\": \"กำลังตรวจสอบ...\", \"Message_Upload\": \"กำลังอัพโหลด...\", \"Message_NoLink\": \"ไม่พบลิงก์ถาวรในการตอบสนอง!\", \"Message_NoSettings\": \"ไม่มีไฟล์การตั้งค่า\", \"Message_Saved\": \"บันทึกการตั้งค่า\",\"SettingsForm_Reset\":\"รีเซ็ตการตั้งค่าทั้งหมดไหม\",\"SettingsForm_Sure\":\"คุณแน่ใจไหม?\",\"SettingsForm_Context\":\"เพิ่มในเมนูบริบท?\",\"SettingsForm_ResetBtn\":\"รีเซ็ต\" }",
			["TraditionalChinese"] = "{ \"MainForm_DragFile\": \"請將檔案拖放到此處\", \"MainForm_More\": \"設置\", \"SettingsForm_Title\": \"設定\", \"SettingsForm_General\": \"一般設定\", \"SettingsForm_Key\": \"API 金鑰\", \"SettingsForm_Get\": \"取得 API 金鑰\", \"SettingsForm_Language\": \"語言\", \"SettingsForm_Save\": \"儲存\", \"SettingsForm_Open\": \"開啟設定檔\", \"SettingsForm_DirectUpload\": \"自動上傳？\", \"UploadForm_Info\": \"檔案資訊\", \"UploadForm_Upload\": \"上傳\", \"UploadForm_Cancel\": \"取消\", \"UploadForm_NoApiKey\": \"尚未輸入一個有效的 API 金鑰。請點選設定並新增一個。\", \"UploadForm_InvalidLength\": \"無效的 API 金鑰長度。金鑰必須包含 64 個字元。\", \"UploadForm_InvalidKey\": \"無效的 API 金鑰\", \"Message_Idle\": \"閒置\", \"Message_Init\": \"正在初始化...\", \"Message_Check\": \"正在檢查...\", \"Message_Upload\": \"正在上傳...\", \"Message_NoLink\": \"無法從回應中找到固定連結!\", \"Message_NoSettings\": \"設定檔不存在\", \"Message_Saved\": \"設定已儲存\",\"SettingsForm_Reset\":\"重置所有設置？\",\"SettingsForm_Sure\":\"你確定嗎？\",\"SettingsForm_Context\":\"添加到上下文菜單？\",\"SettingsForm_ResetBtn\":\"重啟\" }",
			["Turkish"] = "{ \"MainForm_DragFile\": \"Dosyayı buraya sürükleyin\", \"MainForm_More\": \"Ayarlar\", \"SettingsForm_Title\": \"Ayarlar\", \"SettingsForm_General\": \"Genel ayarlar\", \"SettingsForm_Key\": \"API anahtarı\", \"SettingsForm_Get\": \"API anahtarını alın\", \"SettingsForm_Language\": \"Lisan\", \"SettingsForm_Save\": \"Kaydet\", \"SettingsForm_Open\": \"Ayarlar dosyalarını açın\", \"UploadForm_Info\": \"Dosya bilgisi\", \"UploadForm_Upload\": \"Yükle\", \"UploadForm_Cancel\": \"İptal\", \"UploadForm_NoApiKey\": \"API anahtarı girmediniz. Lütfen ayarlara gidin ve bir tane ekleyin.\", \"UploadForm_InvalidLength\": \"Geçersiz API anahtar uzunluğu. Anahtar 64 karakter içermelidir.\", \"UploadForm_InvalidKey\": \"Geçersiz API anahtarı\", \"Message_Idle\": \"Boşta.\", \"Message_Init\": \"Başlatılıyor...\", \"Message_Check\": \"Kontrol ediliyor...\", \"Message_Upload\": \"Yükleniyor...\", \"Message_NoLink\": \"Hiçbir kalıcı link yanıt olarak bulunamadı!\", \"Message_NoSettings\": \"Ayarlar dosyası yok.\", \"Message_Saved\": \"Kaydedilen ayarlar.\",\"SettingsForm_Reset\":\"Bütün ayarları sıfırlamak?\",\"SettingsForm_Sure\":\"Emin misin?\",\"SettingsForm_Context\":\"Bağlam Menüsüne Eklensin mi?\",\"SettingsForm_ResetBtn\":\"Sıfırla\", \"SettingsForm_DirectUpload\": \"Otomatik Yükleme?\" }",
			["Vietnamese"] = "{ \"MainForm_DragFile\": \"Thả tệp tại đây.\", \"MainForm_More\": \"Cài đặt\", \"SettingsForm_Title\": \"Cài đặt\", \"SettingsForm_General\": \"Cài đặt chung\", \"SettingsForm_Key\": \"Khoá API\", \"SettingsForm_Get\": \"Nhận khoá API\", \"SettingsForm_Language\": \"Ngôn ngữ\", \"SettingsForm_Save\": \"Lưu\", \"SettingsForm_Open\": \"Mở tệp cài đặt\", \"SettingsForm_DirectUpload\": \"Tải lên tự động?\", \"UploadForm_Info\": \"Thông tin tệp\", \"UploadForm_Upload\": \"Tải lên\", \"UploadForm_Cancel\": \"Huỷ\", \"UploadForm_NoApiKey\": \"Bạn chưa nhập khoá API. Vui lòng mở cài đặt và thêm một cái.\", \"UploadForm_InvalidLength\": \". Độ dài tối đa của khoá API là 60 chữ cái.\", \"UploadForm_InvalidKey\": \"Khoá API không hợp lệ\", \"Message_Idle\": \"\", \"Message_Init\": \"Đang khởi tạo...\", \"Message_Check\": \"Đang kiểm tra...\", \"Message_Upload\": \"Đang tải lên...\", \"Message_NoLink\": \"Không tìm thấy liên kết cố định nào trong phản hồi.\", \"Message_NoSettings\": \"Không tìm thấy tệp cài đặt.\", \"Message_Saved\": \"Thay đổi của bạn đã được lưu.\",\"SettingsForm_Reset\":\"Đặt lại tất cả các thiết lập?\",\"SettingsForm_Sure\":\"Bạn có chắc không?\",\"SettingsForm_Context\":\"Thêm vào Menu ngữ cảnh?\",\"SettingsForm_ResetBtn\":\"Cài lại\" }"
		};

		public static string[] GetLanguages()
        {
			return Languages.Keys.ToArray();
        }

        public static void Load(string lang)
        {
            Base = JsonConvert.DeserializeObject<LocalizationBase>(Languages[lang]);
        }

        public static void Update()
        {
            var settings = Settings.LoadSettings();
            if (!string.IsNullOrEmpty(settings.Language))
            {
                Load(settings.Language);
            }
            else
            {
                Base = new LocalizationBase();
            }
        }

        // Used to create Json for new version
        public static void Export()
        {
            Base = new LocalizationBase();
            var serialized = JsonConvert.SerializeObject(LocalizationHelper.Base);
            File.WriteAllText("export.json", serialized);
        }
    }
}
